### ISSUE TITLE
Rails 3.2.2 Deprecation Warnings

### ISSUE THREAD

**Issue by msepcot** [CompanyBook/massive_record#88]
DEPRECATION WARNING: ActiveSupport::Memoizable is deprecated and will be removed in future releases,simply use Ruby memoization pattern instead.

```
.../activesupport-3.2.2/lib/active_support/memoizable.rb:8:in `extended'
.../massive_record-0.2.1/lib/massive_record/orm/config.rb:12:in `extend'
.../massive_record-0.2.1/lib/massive_record/orm/config.rb:12:in `<module:ClassMethods>'
.../massive_record-0.2.1/lib/massive_record/orm/config.rb:11:in `<module:Config>'
.../massive_record-0.2.1/lib/massive_record/orm/config.rb:3:in `<module:ORM>'
.../massive_record-0.2.1/lib/massive_record/orm/config.rb:2:in `<module:MassiveRecord>'
.../massive_record-0.2.1/lib/massive_record/orm/config.rb:1:in `<top (required)>'
.../activesupport-3.2.2/lib/active_support/dependencies.rb:251:in `require'
.../activesupport-3.2.2/lib/active_support/dependencies.rb:251:in `block in require'
.../activesupport-3.2.2/lib/active_support/dependencies.rb:236:in `load_dependency'
.../activesupport-3.2.2/lib/active_support/dependencies.rb:251:in `require'
.../massive_record-0.2.1/lib/massive_record/orm/base.rb:13:in `<top (required)>'
.../activesupport-3.2.2/lib/active_support/dependencies.rb:251:in `require'
.../activesupport-3.2.2/lib/active_support/dependencies.rb:251:in `block in require'
.../activesupport-3.2.2/lib/active_support/dependencies.rb:236:in `load_dependency'
.../activesupport-3.2.2/lib/active_support/dependencies.rb:251:in `require'
.../massive_record-0.2.1/lib/massive_record.rb:10:in `<top (required)>'
.../bundler-1.0.21/lib/bundler/runtime.rb:68:in `require'
.../bundler-1.0.21/lib/bundler/runtime.rb:68:in `block (2 levels) in require'
.../bundler-1.0.21/lib/bundler/runtime.rb:66:in `each'
.../bundler-1.0.21/lib/bundler/runtime.rb:66:in `block in require'
.../bundler-1.0.21/lib/bundler/runtime.rb:55:in `each'
.../bundler-1.0.21/lib/bundler/runtime.rb:55:in `require'
.../bundler-1.0.21/lib/bundler.rb:122:in `require'
.../myapp/config/application.rb:18:in `<top (required)>'
.../railties-3.2.2/lib/rails/commands.rb:53:in `require'
.../railties-3.2.2/lib/rails/commands.rb:53:in `block in <top (required)>'
.../railties-3.2.2/lib/rails/commands.rb:50:in `tap'
.../railties-3.2.2/lib/rails/commands.rb:50:in `<top (required)>'
script/rails:6:in `require'
script/rails:6:in `<main>'
```

DEPRECATION WARNING: Specifying an empty prefix/suffix for an attribute method is no longer necessary. If the un-prefixed/suffixed version of the method has not been defined when `define_attribute_methods` is called, it will be defined automatically.

```
.../activemodel-3.2.2/lib/active_model/attribute_methods.rb:359:in `initialize'
.../activemodel-3.2.2/lib/active_model/attribute_methods.rb:181:in `new'
.../activemodel-3.2.2/lib/active_model/attribute_methods.rb:181:in `block in attribute_method_suffix'
.../activemodel-3.2.2/lib/active_model/attribute_methods.rb:181:in `map'
.../activemodel-3.2.2/lib/active_model/attribute_methods.rb:181:in `attribute_method_suffix'
.../massive_record-0.2.1/lib/massive_record/orm/attribute_methods/read.rb:8:in `block in <module:Read>'
.../activesupport-3.2.2/lib/active_support/concern.rb:119:in `class_eval'
.../activesupport-3.2.2/lib/active_support/concern.rb:119:in `append_features'
.../massive_record-0.2.1/lib/massive_record/orm/base.rb:286:in `include'
.../massive_record-0.2.1/lib/massive_record/orm/base.rb:286:in `block in <module:ORM>'
.../massive_record-0.2.1/lib/massive_record/orm/base.rb:279:in `class_eval'
.../massive_record-0.2.1/lib/massive_record/orm/base.rb:279:in `<module:ORM>'
.../massive_record-0.2.1/lib/massive_record/orm/base.rb:33:in `<module:MassiveRecord>'
.../massive_record-0.2.1/lib/massive_record/orm/base.rb:32:in `<top (required)>'
.../activesupport-3.2.2/lib/active_support/dependencies.rb:251:in `require'
.../activesupport-3.2.2/lib/active_support/dependencies.rb:251:in `block in require'
.../activesupport-3.2.2/lib/active_support/dependencies.rb:236:in `load_dependency'
.../activesupport-3.2.2/lib/active_support/dependencies.rb:251:in `require'
.../massive_record-0.2.1/lib/massive_record.rb:10:in `<top (required)>'
.../bundler-1.0.21/lib/bundler/runtime.rb:68:in `require'
.../bundler-1.0.21/lib/bundler/runtime.rb:68:in `block (2 levels) in require'
.../bundler-1.0.21/lib/bundler/runtime.rb:66:in `each'
.../bundler-1.0.21/lib/bundler/runtime.rb:66:in `block in require'
.../bundler-1.0.21/lib/bundler/runtime.rb:55:in `each'
.../bundler-1.0.21/lib/bundler/runtime.rb:55:in `require'
.../bundler-1.0.21/lib/bundler.rb:122:in `require'
.../myapp/config/application.rb:18:in `<top (required)>'
.../railties-3.2.2/lib/rails/commands.rb:53:in `require'
.../railties-3.2.2/lib/rails/commands.rb:53:in `block in <top (required)>'
.../railties-3.2.2/lib/rails/commands.rb:50:in `tap'
.../railties-3.2.2/lib/rails/commands.rb:50:in `<top (required)>'
script/rails:6:in `require'
script/rails:6:in `<main>'
```

DEPRECATION WARNING: The InstanceMethods module inside ActiveSupport::Concern will be no longer included automatically. Please define instance methods directly in MassiveRecord::ORM::DefaultId instead.

```
.../activesupport-3.2.2/lib/active_support/concern.rb:116:in `append_features'
.../massive_record-0.2.1/lib/massive_record/orm/base.rb:293:in `include'
.../massive_record-0.2.1/lib/massive_record/orm/base.rb:293:in `block in <module:ORM>'
.../massive_record-0.2.1/lib/massive_record/orm/base.rb:279:in `class_eval'
.../massive_record-0.2.1/lib/massive_record/orm/base.rb:279:in `<module:ORM>'
.../massive_record-0.2.1/lib/massive_record/orm/base.rb:33:in `<module:MassiveRecord>'
.../massive_record-0.2.1/lib/massive_record/orm/base.rb:32:in `<top (required)>'
.../activesupport-3.2.2/lib/active_support/dependencies.rb:251:in `require'
.../activesupport-3.2.2/lib/active_support/dependencies.rb:251:in `block in require'
.../activesupport-3.2.2/lib/active_support/dependencies.rb:236:in `load_dependency'
.../activesupport-3.2.2/lib/active_support/dependencies.rb:251:in `require'
.../massive_record-0.2.1/lib/massive_record.rb:10:in `<top (required)>'
.../bundler-1.0.21/lib/bundler/runtime.rb:68:in `require'
.../bundler-1.0.21/lib/bundler/runtime.rb:68:in `block (2 levels) in require'
.../bundler-1.0.21/lib/bundler/runtime.rb:66:in `each'
.../bundler-1.0.21/lib/bundler/runtime.rb:66:in `block in require'
.../bundler-1.0.21/lib/bundler/runtime.rb:55:in `each'
.../bundler-1.0.21/lib/bundler/runtime.rb:55:in `require'
.../bundler-1.0.21/lib/bundler.rb:122:in `require'
.../myapp/config/application.rb:18:in `<top (required)>'
.../railties-3.2.2/lib/rails/commands.rb:53:in `require'
.../railties-3.2.2/lib/rails/commands.rb:53:in `block in <top (required)>'
.../railties-3.2.2/lib/rails/commands.rb:50:in `tap'
.../railties-3.2.2/lib/rails/commands.rb:50:in `<top (required)>'
script/rails:6:in `require'
script/rails:6:in `<main>'
```

**Comment by thhermansen** [comment]
It has been a while since I worked for Companybook on MassiveRecord (Rails 3.0 was the last version back then), and I don't think MassiveRecord is compatible with 3.1, nor 3.2.
